#!/usr/bin/env python3

from dice.dice_unit import DiceUnit

#unit = DiceUnit('/dev/snd/hwC1D0')
unit = DiceUnit('/dev/snd/hwC1D0')

print('{0:016x}'.format(unit.read_owner_addr()))
print(unit.read_enabled())
print(unit.read_clock_status())
print(unit.read_clock_detection())
print(unit.read_measured_rate())
print(unit.read_dice_version())
print(unit.get_latest_notification())
print(unit.supported_sampling_rates)
print(unit.supported_clock_sources)
print(unit.get_sampling_rate())
print(unit.get_clock_source())
unit.set_nickname('SndDice')
print(unit.get_nickname())
